### ISSUE TITLE
WGS/WES Compatibility？

### ISSUE THREAD

**Issue by Tesson98** [SinOncology/BreakID#5]
Dear @fionakim @SinOncology, 
    Thanks for releasing and maintaining BreakID, whichi is with fast running speed, low memory usage and extremely high accuracy.
    While this tool is useful with targetted sequencing data, does it also compatible with WGS/WES data? If this tool can not be used with WGS/WES, do you have any advices?  
    Really hope for your suggestions and wish you a good day!
 
Tesson,
6th, Feb, 2023

**Comment by fionakim** [comment]
we had tested BreakID using wes data but not WGS data。 theoretically， It can be applied in WGS data。

**Comment by Tesson98** [comment]
Thanks for your reply. I will try this on my WGS/WES data.
